---
#    _         _          __             _     
#   /_\  _   _| |_ ___   / /  __ _ _ __ (_)___ 
#  //_\\| | | | __/ _ \ / /  / _` | '_ \| / __|
# /  _  \ |_| | || (_) / /__| (_| | |_) | \__ \
# \_/ \_/\__,_|\__\___/\____/\__,_| .__/|_|___/
#                                 |_|          
#
# Amount = The amount of lapis that will be in the enchantment inventory.
# [Default] amount: 3
amount: 3
...